# Google Cloud Build script
#

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --build-arg
  - PYTHON_DEPS=nltk==3.4 numpy==1.16.1 pandas==0.24.1 pandas-gbq==0.9.0 requests==2.21.0 requests-oauthlib==1.2.0 urllib3==1.24.2 google-api-python-client~=1.7 google-auth-httplib2>=0.0.1 google-auth~=1.6 google-cloud-bigquery-datatransfer>=0.4.0 google-cloud-dlp>=0.11.0 google-cloud-pubsub==1.0.0 google-cloud-redis>=0.3.0 google-cloud-speech>=0.36.3 google-cloud-storage~=1.16 google-cloud-tasks==1.2.1 grpcio-gcp>=0.2.2 httplib2~=0.9
  - -t
  - eu.gcr.io/$PROJECT_ID/airflow:1.10.5-custom-log-1
  - .
images: ['eu.gcr.io/$PROJECT_ID/airflow:1.10.5-custom-log-1']
