# Google Cloud Build script
#

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -t
  - eu.gcr.io/$PROJECT_ID/airflow:1.10.5-pubsub
  - .
images: ['eu.gcr.io/$PROJECT_ID/airflow:1.10.5-pubsub']
